[package]
name = "si-scale"
version = "0.1.0"
edition = "2018"

license = "MIT/Apache-2.0"
repository = "https://github.com/u0xy/si-scale"
homepage = "https://github.com/u0xy/si-scale"
documentation = "https://docs.rs/si-scale"
description = """
Formats value with values using the appropriate SI scale. Depending on the attached unit:
- 1337 -> 1.34 kB
- 1337 -> 1_337 s
- 0.1337 -> 133.7 ms
- etc
"""

keywords = ["units", "pretty", "human", "si", "scale"]
readme = "README.md"
categories = ["value-formatting", "science"]
exclude = ["/.github", "/.travis.yml", "/appveyor.yml"]

[dependencies]
