[package]
name = "si-scale"
version = "0.1.1"
edition = "2018"

license = "MIT/Apache-2.0"
repository = "https://github.com/u0xy/si-scale"
homepage = "https://github.com/u0xy/si-scale"
documentation = "https://docs.rs/si-scale"
description = """
Formats values using the appropriate SI scale (could be named `pretty-units`).

seconds(1.3e-5) -> 13 Âµs
"""

keywords = ["units", "pretty", "human", "number", "si-units"]
readme = "README.md"
categories = ["value-formatting", "science"]
exclude = ["/.github", "/.travis.yml", "/appveyor.yml"]

[dependencies]
